[package]
name = "partnest-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "partnest_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = "0.4.45"
rusqlite = { version = "0.40.2", features = ["bundled", "backup"] }
tauri = { version = "2", features = [] }
uuid = { version = "1.24.1", features = ["v7"] }

